/**
 * Public icon-catalog surface. Merges the generated aoe4guides catalog
 * (src/data/generated/icons.ts — regenerated by scripts/sync-aoe4-data.ts) with
 * the hand-maintained aliases in ./aliases.ts, widening IconCategory with
 * "General" so aliases have a home in the picker.
 *
 * The `civs` restriction is plain availability data (from aoe4guides), not view
 * code; `getIconsForCiv` is a query over it, used at selection time.
 */
import {
  ICON_CATALOG as GENERATED_ICON_CATALOG,
  type IconCategory as GeneratedIconCategory,
  type IconEntry as GeneratedIconEntry,
} from "./generated/icons";
import { ICON_ALIASES } from "./aliases";

export type IconCategory = GeneratedIconCategory | "General";

export type IconEntry = Omit<GeneratedIconEntry, "category"> & {
  category: IconCategory;
};

export const ICON_CATEGORIES: readonly IconCategory[] = [
  "General",
  "Resource",
  "Age",
  "Unit",
  "Building",
  "Technology",
] as const;

export const ICON_CATALOG: readonly IconEntry[] = Object.freeze([
  ...ICON_ALIASES,
  ...GENERATED_ICON_CATALOG,
]);

/** Catalog entries available to a given civ. Aliases carry no civ restriction
 *  and therefore appear for every civ. */
export function getIconsForCiv(civId: string): IconEntry[] {
  return ICON_CATALOG.filter((e) => !e.civs || e.civs.includes(civId));
}
